<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pricing</name>
   <tag></tag>
   <elementGuidId>22c08aeb-b9a9-44b5-85bc-c408642f1408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-5.col-md-4.col-sm-12.ftr-menu > ul > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Pricing')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2eec9bb5-5540-4389-8344-73b6b5df2dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/pricing</value>
      <webElementGuid>b1b067ab-8660-40f2-bfec-d457641b9ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pricing </value>
      <webElementGuid>1854a8c8-5a99-4c8c-b604-170389c69afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sticky&quot;]/footer[1]/div[@class=&quot;container container-lg container-xl container-xxl&quot;]/div[@class=&quot;row pb-5&quot;]/div[@class=&quot;col-lg-5 col-md-4 col-sm-12 ftr-menu&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>7a8700d4-5299-40b1-8143-bc23e2cc16e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pricing')])[2]</value>
      <webElementGuid>970c29e6-a941-4014-87a2-fe3c6cb177a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/index.php/pricing')])[2]</value>
      <webElementGuid>be259eb2-2609-469e-8a5c-2f3f6de5d07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>efabd064-d520-49a8-88ff-ad89b49db762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/pricing' and (text() = 'Pricing ' or . = 'Pricing ')]</value>
      <webElementGuid>ea5fbcbd-6748-42d1-99c6-2e7b4f373939</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
