<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manufacturing</name>
   <tag></tag>
   <elementGuidId>ff92aa0e-550f-4e55-a71e-916c3121216d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.nav_dropDown > ul > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-menu']/ul/li[2]/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d1d8243-a804-4ec4-b7c2-b67413f0edfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/manufacturing</value>
      <webElementGuid>e13cfd60-a821-4459-86ba-3408a1385e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manufacturing</value>
      <webElementGuid>00da738f-2b8c-4711-bfa4-c86858bd5567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu&quot;)/ul[@class=&quot;navbar-nav justify-content-center flex-grow-1 pe-3&quot;]/li[@class=&quot;nav-item&quot;]/div[@class=&quot;nav_dropDown&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>2f81437f-f0b7-441c-ae16-45f4f17e58c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-menu']/ul/li[2]/div/ul/li/a</value>
      <webElementGuid>903b7d51-45eb-4bc0-af54-fa5349374fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manufacturing')]</value>
      <webElementGuid>cbdea390-bdd4-4623-b6a2-3d6633108f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/manufacturing')]</value>
      <webElementGuid>78513bf9-6ccd-4cdf-8b16-04a456910c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/a</value>
      <webElementGuid>f0895d2b-2b39-45d4-9a29-d310da9cc1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/manufacturing' and (text() = 'Manufacturing' or . = 'Manufacturing')]</value>
      <webElementGuid>401b12ba-d82f-4918-ace4-da9574b4da8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
